#!/usr/bin/env python

import os, sys
import subprocess

fp = open('user_accounts')
for line in fp:
    line = line.strip()
    if not line or line.startswith('#'):
        continue
    user, authorized_key = line.split(None, 1)
    homedir = os.path.join('/home', user)
    if not os.path.exists(homedir):
        print 'Creating user %s' % user
        subprocess.call(
            ['useradd', user])
    else:
        print 'User %s already exists' % user
    ssh_dir = os.path.join(homedir, '.ssh')
    if not os.path.exists(ssh_dir):
        os.makedirs(ssh_dir)
    print 'writing authorized_keys in %s' % ssh_dir
    fp = open(os.path.join(ssh_dir, 'authorized_keys'), 'a')
    fp.write(authorized_key+'\n')
    fp.close()
